apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        release: "0"
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.5-jessie
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
      volumes: 
        - name: mongo-volume
          
          persistentVolumeClaim:
            claimName: mongo-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
   
spec:
  selector:
      app: mongodb

  ports:
    - name: http
      port: 27017
      nodePort: 30050

  type: NodePort
