apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
    release: "0"
  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  name: service-backend
  labels:
      app: backend
      
spec:
  selector:
      app: backend

  ports:
    - name: http
      port: 8161
      nodePort: 30010

  type: NodePort


